name: Acceptance Cycle

on:
  workflow_run:
    workflows: ["Commit Cycle"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'

      - name: Run tests
        run: flutter test
