name: Commit Cycle
run-name: Commit Cycle

on:
  workflow_dispatch:
      inputs:
          logLevel:
            description: 'Log level'
            required: true
            default: 'warning'
            type: choice
            options:
            - info
            - warning
            - debug
          runner:
            description: "Runner Agent"
            required: true
            default: 'ubuntu-latest'
            type: choice
            options:
            - ubuntu-latest
            - self-hosted

  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on:  ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.runner || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze
