name: Commit Cycle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

  trigger_acceptance_cycle:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Trigger Acceptance Cycle
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: workflowRuns } = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file: 'acceptance_cycle.yml',
              status: 'completed'
            });
            
            const successfulRuns = workflowRuns.workflow_runs.filter(run => run.conclusion === 'success');
            if (successfulRuns.length === 0) {
              await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_file: 'acceptance_cycle.yml',
                ref: 'develop'
              });
            }
