name: Commit Cycle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

  trigger_acceptance_cycle:
    needs: build
    runs-on: ubuntu-latest
    if: success()
  
    steps:
      - name: Get Workflow ID
        id: get_workflow_id
        run: |
          echo "::set-output name=workflow_id::$(curl -s -X GET \
          -H \"Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}\" \
          -H \"Accept: application/vnd.github.v3+json\" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows | \
          jq '.workflows[] | select(.name == \"acceptance_cycle.yml\") | .id')"
  
      - name: Trigger Acceptance Cycle
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflowId = ${{ steps.get_workflow_id.outputs.workflow_id }};
            if (workflowId) {
              await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflowId,
                ref: 'develop'
              });
            } else {
              console.error('Workflow ID not found.');
            }

