name: Push to Master

on:
  workflow_run:
    workflows: ["Acceptance Cycle"]
    types:
      - completed

jobs:
  push_to_master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Increment Counter
        id: increment_counter
        run: |
          if [ -f counter.txt ]; then
            count=$(cat counter.txt)
            count=$((count + 1))
            echo "$count" > counter.txt
          else
            echo "1" > counter.txt
          fi

      - name: Push to Master
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');

            const files = fs.readdirSync(path.resolve(__dirname));

            await Promise.all(files.map(async (file) => {
              const fileContent = fs.readFileSync(file, 'utf8');
              await github.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: file,
                message: 'Update to master branch',
                content: Buffer.from(fileContent).toString('base64'),
                branch: 'master',
                committer: {
                  name: 'GitHub Actions',
                  email: 'actions@github.com'
                },
                author: {
                  name: 'GitHub Actions',
                  email: 'actions@github.com'
                }
              });
            }));

      - name: Upload Counter Artifact
        uses: actions/upload-artifact@v2
        with:
          name: push-counter
          path: counter.txt
