name: Push to Master

on:
  workflow_run:
    workflows: ["Acceptance Cycle"]
    types:
      - completed

jobs:
  push_to_master:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Increment Counter
        id: increment_counter
        run: |
          cd $GITHUB_WORKSPACE
          if [ -f counter.txt ]; then
            count=$(cat counter.txt)
            count=$((count + 1))
            echo "$count" > counter.txt
          else
            echo "1" > counter.txt
          fi

      - name: Push to Master
        run: |
          git config --global user.email "victor.delamonica@epitech.eu"
          git config --global user.name "VictorDelamonica"
          git fetch origin develop
          count=$(cat counter.txt)
          git merge -s recursive -X ours --allow-unrelated-histories --no-ff develop "Merge from develop (#$count)"
          git push origin master

      - name: Upload Counter Artifact
        uses: actions/upload-artifact@v2
        with:
          name: push-counter
          path: counter.txt
