name: Release Cycle
run-name: Release Cycle

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      runner:
        description: "Runner Agent"
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - self-hosted

jobs:
  run_test:
    runs-on: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.runner || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'

      - name: Build APK
        run: |
          flutter build apk --release
          versionCode=$(cat build/app/outputs/flutter-apk/app-release.properties | grep "versionCode" | cut -d'=' -f2)
          versionName=$(cat build/app/outputs/flutter-apk/app-release.properties | grep "versionName" | cut -d'=' -f2)
          echo "Version Code: $versionCode"
          echo "Version Name: $versionName"
          echo "New Version Name: $((versionName + 1))" > new_version.txt
      - name: Upload APK and Version File
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            new_version.txt

      - name: Release APK
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release ${{ github.run_number }}
